/*
 *  generated by CSeq [ 0000 / 0000 ]
 * 
 *  instance version    {}
 *
 *  2019-09-03 09:07:43
 *
 *  params:
 *    -l datarace, --unwind 1, --rounds 1, --debug , --variable-array-size 2, --local-vars 2, --seq , -i /home/salvatore/ShadowMemory/SM-DR-Verismart/Exp-debian/currentSet/original/sndfile-tools-1.03_src_sndfile-jackplay.c, 
 *
 */
#define __cs_MUTEX_INITIALIZER -1
#define __cs_COND_INITIALIZER -1
#define __cs_RWLOCK_INITIALIZER -1
#define __cs_BARRIER_SERIAL_THREAD 0
#define __cs_CANCEL_ASYNCHRONOUS 0
#define __cs_CANCEL_ENABLE 0
#define __cs_CANCEL_DEFERRED 0
#define __cs_CANCEL_DISABLE 0
#define __cs_CANCELED 0
#define __cs_CREATE_DETACHED 0
#define __cs_CREATE_JOINABLE 0
#define __cs_EXPLICIT_SCHED 0
#define __cs_INHERIT_SCHED 0
#define __cs_MUTEX_DEFAULT 0
#define __cs_MUTEX_ERRORCHECK 0
#define __cs_MUTEX_NORMAL 0
#define __cs_MUTEX_RECURSIVE 0
#define __cs_MUTEX_ROBUST 0
#define __cs_MUTEX_STALLED 0
#define __cs_ONCE_INIT 0
#define __cs_PRIO_INHERIT 0
#define __cs_PRIO_NONE 0
#define __cs_PRIO_PROTECT 0
#define __cs_PROCESS_SHARED 0
#define __cs_PROCESS_PRIVATE 0
#define __cs_SCOPE_PROCESS 0
#define __cs_SCOPE_SYSTEM 0
int __VERIFIER_nondet_int();
int nondet_int();
unsigned int __VERIFIER_nondet_uint();
unsigned int nondet_uint();
_Bool __VERIFIER_nondet_bool();
_Bool nondet_bool();
char __VERIFIER_nondet_char();
char nondet_char();
unsigned char __VERIFIER_nondet_uchar();
unsigned char nondet_uchar();
#define THREADS 1
#define ROUNDS 1
#define STOP_VOID(A) return;
#define STOP_NONVOID(A) return 0;
#define IF(T,A,B) if ((__cs_pc[T] > A) | (A >= __cs_pc_cs[T])) goto B; 

                                        unsigned __CPROVER_bitvector[1] __cs_active_thread[2] = {1};
                                        unsigned __CPROVER_bitvector[4] __cs_pc[2];
                                        unsigned __CPROVER_bitvector[5] __cs_pc_cs[2];
                                        unsigned __CPROVER_bitvector[1] __cs_last_thread;
                                        unsigned __CPROVER_bitvector[4] __cs_thread_lines[2] = {10, 13};
                                        void *malloc(unsigned long int);
                                        void *__cs_safe_malloc(unsigned int __cs_size)
                                        {
                                                  void *__cs_ptr = (malloc(__cs_size));
                                                  return __cs_ptr;
                                        }
                                        void __CSEQ_message(char *__cs_message)
                                        {
                                                  ;
                                        }
                                        typedef int __cs_t;
                                        void *__cs_threadargs[2];
                                        void *__cs_thread_joinargs[2];
                                        int __cs_create(__cs_t *__cs_new_thread_id, void *__cs_attr, void *(*__cs_thread_function)(void *), void *__cs_arg, int __cs_threadID)
                                        {
                                                  if (__cs_threadID > THREADS)
                                                            return 0;
                                                  *__cs_new_thread_id = __cs_threadID;
                                                  __cs_active_thread[__cs_threadID] = 1;
                                                  __cs_threadargs[__cs_threadID] = __cs_arg;
                                                  __CSEQ_message("thread spawned");
                                                  return 0;
                                        }
                                        int __cs_join(__cs_t __cs_id, void **__cs_value_ptr)
                                        {
                                                  __CPROVER_assume(__cs_pc[__cs_id] == __cs_thread_lines[__cs_id]);
                                                  *__cs_value_ptr = __cs_thread_joinargs[__cs_id];
                                                  return 0;
                                        }
                                        int __cs_exit(void *__cs_value_ptr, unsigned int __cs_thread_index)
                                        {
                                                  __cs_thread_joinargs[__cs_thread_index] = __cs_value_ptr;
                                                  return 0;
                                        }
                                        int __cs_self(void)
                                        {
                                                  return 1;
                                        }
                                        typedef int __cs_mutex_t;
                                        int __cs_mutex_init(__cs_mutex_t *__cs_m, int __cs_val)
                                        {
                                                  *__cs_m = -1;
                                                  return 0;
                                        }
                                        int __cs_mutex_destroy(__cs_mutex_t *__cs_mutex_to_destroy)
                                        {
                                                  __CPROVER_assume((*__cs_mutex_to_destroy) == (-1));
                                                  *__cs_mutex_to_destroy = -2;
                                                  __CSEQ_message("lock destroyed");
                                                  return 0;
                                        }
                                        int __cs_mutex_lock(__cs_mutex_t *__cs_mutex_to_lock, unsigned __CPROVER_bitvector[1] __cs_thread_index)
                                        {
                                                  __CPROVER_assume((*__cs_mutex_to_lock) == (-1));
                                                  *__cs_mutex_to_lock = __cs_thread_index + 1;
                                                  __CSEQ_message("lock acquired");
                                                  return 0;
                                        }
                                        int __cs_mutex_unlock(__cs_mutex_t *__cs_mutex_to_unlock, unsigned __CPROVER_bitvector[1] __cs_thread_index)
                                        {
                                                  __CPROVER_assume((*__cs_mutex_to_unlock) == (__cs_thread_index + 1));
                                                  *__cs_mutex_to_unlock = -1;
                                                  __CSEQ_message("lock released");
                                                  return 0;
                                        }
                                        typedef int __cs_rwlock_t;
                                        int __cs_rwlock_init(__cs_rwlock_t *__cs_rwlock, int _cs_val)
                                        {
                                                  *__cs_rwlock = -1;
                                                  return 0;
                                        }
                                        int __cs_rwlock_rdlock(__cs_rwlock_t *__cs_rwlock, unsigned int __cs_thread_index)
                                        {
                                                  __CPROVER_assume((*__cs_rwlock) == (-1));
                                                  *__cs_rwlock = __cs_thread_index + 1;
                                                  __CSEQ_message("rwlock read acquired");
                                                  return 0;
                                        }
                                        int __cs_rwlock_unlock(__cs_rwlock_t *__cs_rwlock, unsigned int __cs_thread_index)
                                        {
                                                  __CPROVER_assume((*__cs_rwlock) == (__cs_thread_index + 1));
                                                  *__cs_rwlock = -1;
                                                  __CSEQ_message("lock released");
                                                  return 0;
                                        }
                                        int __cs_rwlock_wrlock(__cs_rwlock_t *__cs_rwlock, unsigned int __cs_thread_index)
                                        {
                                                  __CPROVER_assume((*__cs_rwlock) == (-1));
                                                  *__cs_rwlock = __cs_thread_index + 1;
                                                  __CSEQ_message("rwlock write acquired");
                                                  return 0;
                                        }
                                        int __cs_rwlock_destroy(__cs_rwlock_t *__cs_rwlock)
                                        {
                                                  __CPROVER_assume((*__cs_rwlock) == (-1));
                                                  *__cs_rwlock = -2;
                                                  __CSEQ_message("lock destroyed");
                                                  return 0;
                                        }
                                        typedef int __cs_sem_t;
                                        int __cs_sem_init(__cs_sem_t *sem, int pshared, unsigned int value)
                                        {
                                                  *sem = 2;
                                                  return 0;
                                        }
                                        int __cs_sem_wait(__cs_sem_t *sem)
                                        {
                                                  __CPROVER_assume((*sem) == 2);
                                                  *sem = 1;
                                                  __CSEQ_message("semaphore locked");
                                                  return 0;
                                        }
                                        int __cs_sem_post(__cs_sem_t *sem)
                                        {
                                                  __CPROVER_assume((*sem) == 1);
                                                  *sem = 2;
                                                  __CSEQ_message("semaphore unlocked");
                                                  return 0;
                                        }
                                        int __cs_sem_destroy(__cs_sem_t *sem)
                                        {
                                                  __CPROVER_assume((*sem) == 2);
                                                  *sem = -1;
                                                  __CSEQ_message("semaphore destroyed");
                                                  return 0;
                                        }
                                        typedef int __cs_spinlock_t;
                                        int __cs_spin_init(__cs_spinlock_t *__cs_lock, int _cs_val)
                                        {
                                                  *__cs_lock = -1;
                                                  return 0;
                                        }
                                        int __cs_spin_lock(__cs_spinlock_t *__cs_lock, unsigned int __cs_thread_index)
                                        {
                                                  __CPROVER_assume((*__cs_lock) == (-1));
                                                  *__cs_lock = __cs_thread_index + 1;
                                                  __CSEQ_message("spinlock acquired");
                                                  return 0;
                                        }
                                        int __cs_spin_unlock(__cs_spinlock_t *__cs_lock, unsigned int __cs_thread_index)
                                        {
                                                  __CPROVER_assume((*__cs_lock) == (__cs_thread_index + 1));
                                                  *__cs_lock = -1;
                                                  __CSEQ_message("spinlock released");
                                                  return 0;
                                        }
                                        int __cs_spin_destroy(__cs_spinlock_t *__cs_lock)
                                        {
                                                  __CPROVER_assume((*__cs_lock) == (-1));
                                                  *__cs_lock = -2;
                                                  __CSEQ_message("lock destroyed");
                                                  return 0;
                                        }
                                        typedef int __cs_cond_t;
                                        int __cs_cond_init(__cs_cond_t *__cs_cond_to_init, void *__cs_attr)
                                        {
                                                  *__cs_cond_to_init = -1;
                                                  return 0;
                                        }
                                        int __cs_cond_destroy(__cs_cond_t *__cs_cond_to_destroy)
                                        {
                                                  *__cs_cond_to_destroy = -2;
                                                  return 0;
                                        }
                                        int __cs_cond_wait_1(__cs_cond_t *__cs_cond_to_wait_for, __cs_mutex_t *__cs_m, unsigned int __cs_thread_index)
                                        {
                                                  __CPROVER_assume((*__cs_cond_to_wait_for) != 0);
                                                  __CPROVER_assume((*__cs_cond_to_wait_for) != (-2));
                                                  __cs_mutex_unlock(__cs_m, __cs_thread_index);
                                                  return 0;
                                        }
                                        int __cs_cond_wait_2(__cs_cond_t *__cs_cond_to_wait_for, __cs_mutex_t *__cs_m, unsigned int __cs_thread_index)
                                        {
                                                  __CPROVER_assume((*__cs_cond_to_wait_for) == 1);
                                                  __cs_mutex_lock(__cs_m, __cs_thread_index);
                                                  return 0;
                                        }
                                        int __cs_cond_signal(__cs_cond_t *__cs_cond_to_signal)
                                        {
                                                  *__cs_cond_to_signal = 1;
                                                  __CSEQ_message("conditional variable signal");
                                                  return 0;
                                        }
                                        int __cs_cond_broadcast(__cs_cond_t *__cs_cond_to_broadcast)
                                        {
                                                  *__cs_cond_to_broadcast = 1;
                                                  __CSEQ_message("conditional variable broadcast");
                                                  return 0;
                                        }
                                        typedef struct __cs_barrier_t
                                        {
                                                  unsigned int init;
                                                  unsigned int current;
                                        } __cs_barrier_t;
                                        int __cs_barrier_init(__cs_barrier_t *__cs_barrier_to_init, void *__cs_attr, unsigned int count)
                                        {
                                                  __CPROVER_assume(count > 0);
                                                  __cs_barrier_to_init->current = count;
                                                  __cs_barrier_to_init->init = count;
                                                  return 0;
                                        }
                                        int __cs_barrier_destroy(__cs_barrier_t *__cs_barrier_to_destroy)
                                        {
                                                  __cs_barrier_to_destroy->init = -1;
                                                  __cs_barrier_to_destroy->current = -1;
                                                  return 0;
                                        }
                                        int __cs_barrier_wait_1(__cs_barrier_t *__cs_barrier_to_wait)
                                        {
                                                  __CPROVER_assume(__cs_barrier_to_wait->init > 0);
                                                  __cs_barrier_to_wait->current--;
                                                  return 0;
                                        }
                                        int __cs_barrier_wait_2(__cs_barrier_t *__cs_barrier_to_wait)
                                        {
                                                  __CPROVER_assume(__cs_barrier_to_wait->init > 0);
                                                  __CPROVER_assume(__cs_barrier_to_wait->current == 0);
                                                  __cs_barrier_to_wait->current = __cs_barrier_to_wait->init;
                                                  return 0;
                                        }
                                        typedef int __cs_attr_t;
                                        struct sched_param
                                        {
                                                  signed int sched_priority;
                                        };
                                        int __cs_attr_init(__cs_attr_t *t)
                                        {
                                                  return 0;
                                        }
                                        int __cs_attr_destroy(__cs_attr_t *t)
                                        {
                                                  return 0;
                                        }
                                        int __cs_attr_getdetachstate(const __cs_attr_t *t, int *s)
                                        {
                                                  return 0;
                                        }
                                        int __cs_attr_getguardsize(const __cs_attr_t *t, unsigned int *s)
                                        {
                                                  return 0;
                                        }
                                        int __cs_attr_getinheritsched(const __cs_attr_t *t, int *s)
                                        {
                                                  return 0;
                                        }
                                        int __cs_attr_getschedparam(const __cs_attr_t *t, struct sched_param *s)
                                        {
                                                  return 0;
                                        }
                                        int __cs_attr_getschedpolicy(const __cs_attr_t *t, int *s)
                                        {
                                                  return 0;
                                        }
                                        int __cs_attr_getscope(const __cs_attr_t *t, int *s)
                                        {
                                                  return 0;
                                        }
                                        int __cs_attr_getstackaddr(const __cs_attr_t *t, void **s)
                                        {
                                                  return 0;
                                        }
                                        int __cs_attr_getstacksize(const __cs_attr_t *t, unsigned int *s)
                                        {
                                                  return 0;
                                        }
                                        int __cs_attr_setdetachstate(__cs_attr_t *t, int s)
                                        {
                                                  return 0;
                                        }
                                        int __cs_attr_setguardsize(__cs_attr_t *t, unsigned int s)
                                        {
                                                  return 0;
                                        }
                                        int __cs_attr_setinheritsched(__cs_attr_t *t, int s)
                                        {
                                                  return 0;
                                        }
                                        int __cs_attr_setschedparam(__cs_attr_t *t, const struct sched_param *s)
                                        {
                                                  return 0;
                                        }
                                        int __cs_attr_setschedpolicy(__cs_attr_t *t, int s)
                                        {
                                                  return 0;
                                        }
                                        int __cs_attr_setscope(__cs_attr_t *t, int s)
                                        {
                                                  return 0;
                                        }
                                        int __cs_attr_setstackaddr(__cs_attr_t *t, void *s)
                                        {
                                                  return 0;
                                        }
                                        int __cs_attr_setstacksize(__cs_attr_t *t, unsigned int s)
                                        {
                                                  return 0;
                                        }
                                        _Bool __cs_dataraceDetectionStarted = (0);
                                        _Bool __cs_dataraceSecondThread = (0);
                                        _Bool __cs_dataraceNotDetected = (1);
                                        _Bool __cs_dataraceContinue = (1);
                                        struct anonymous;
                                        struct anonymous$2;
                                        struct anonymous$0;
                                        union anonymous$1;
                                        union anonymous$3;
                                        struct SF_INFO;
                                        struct SNDFILE_tag;
                                        struct _IO_FILE;
                                        struct _IO_marker;
                                        struct __pthread_internal_list;
                                        struct __pthread_mutex_s;
                                        struct _jack_client;
                                        struct _jack_port;
                                        struct _thread_info;
                                        union pthread_attr_t;
                                        void *calloc(unsigned long int, unsigned long int);
                                        static void *disk_thread_0(void *__cs_param__arg);
                                        void exit(signed int);
                                        signed int fflush(struct _IO_FILE *);
                                        double fmod(double, double);
                                        signed int fprintf(struct _IO_FILE *, const char *, ...);
                                        void free(void *);
                                        signed int jack_activate(struct _jack_client *);
                                        signed int jack_client_close(struct _jack_client *);
                                        struct _jack_client *jack_client_new(const char *);
                                        signed int jack_connect(struct _jack_client *, const char *, const char *);
                                        unsigned int jack_get_sample_rate(struct _jack_client *);
                                        void jack_on_shutdown(struct _jack_client *, void (*)(void *), void *);
                                        void *jack_port_get_buffer(struct _jack_port *, unsigned int);
                                        const char *jack_port_name(const struct _jack_port *);
                                        struct _jack_port *jack_port_register(struct _jack_client *, const char *, const char *, unsigned long int, unsigned long int);
                                        struct anonymous$2 *jack_ringbuffer_create(unsigned long int);
                                        void jack_ringbuffer_free(struct anonymous$2 *);
                                        void jack_ringbuffer_get_write_vector(const struct anonymous$2 *, struct anonymous *);
                                        unsigned long int jack_ringbuffer_read(struct anonymous$2 *, char *, unsigned long int);
                                        void jack_ringbuffer_write_advance(struct anonymous$2 *, unsigned long int);
                                        signed int jack_set_process_callback(struct _jack_client *, signed int (*)(unsigned int, void *), void *);
                                        static void jack_shutdown(void *__cs_param__arg);
                                        void *memset(void *, signed int, unsigned long int);
                                        static void print_time(unsigned int __cs_param__pos, signed int __cs_param__jack_sr);
                                        static signed int process(unsigned int __cs_param__nframes, void *__cs_param__arg);
                                        signed int pthread_cond_signal(union anonymous$1 *);
                                        signed int pthread_cond_wait(union anonymous$1 *, union anonymous$3 *);
                                        signed int pthread_create(unsigned long int *, const union pthread_attr_t *, void *(*)(void *), void *);
                                        signed int pthread_mutex_lock(union anonymous$3 *);
                                        signed int pthread_mutex_trylock(union anonymous$3 *);
                                        signed int pthread_mutex_unlock(union anonymous$3 *);
                                        signed int pthread_setcanceltype(signed int, signed int *);
                                        signed int puts(const char *);
                                        signed int sf_close(struct SNDFILE_tag *);
                                        struct SNDFILE_tag *sf_open(const char *, signed int, struct SF_INFO *);
                                        signed long int sf_readf_float(struct SNDFILE_tag *, float *, signed long int);
                                        signed int snprintf(char *, unsigned long int, const char *, ...);
                                        signed int usleep(unsigned int);
                                        struct anonymous
                                        {
                                                  char *buf;
                                                  unsigned long int len;
                                        };
                                        struct anonymous$2
                                        {
                                                  char *buf;
                                                  unsigned long int write_ptr;
                                                  unsigned long int read_ptr;
                                                  unsigned long int size;
                                                  unsigned long int size_mask;
                                                  signed int mlocked;
                                        };
                                        struct anonymous$0
                                        {
                                                  signed int __lock;
                                                  unsigned int __futex;
                                                  unsigned long long int __total_seq;
                                                  unsigned long long int __wakeup_seq;
                                                  unsigned long long int __woken_seq;
                                                  void *__mutex;
                                                  unsigned int __nwaiters;
                                                  unsigned int __broadcast_seq;
                                        };
                                        union anonymous$1
                                        {
                                                  struct anonymous$0 __data;
                                                  char __size[48l];
                                                  signed long long int __align;
                                        };
                                        struct __pthread_internal_list
                                        {
                                                  struct __pthread_internal_list *__prev;
                                                  struct __pthread_internal_list *__next;
                                        };
                                        struct __pthread_mutex_s
                                        {
                                                  signed int __lock;
                                                  unsigned int __count;
                                                  signed int __owner;
                                                  unsigned int __nusers;
                                                  signed int __kind;
                                                  signed short int __spins;
                                                  signed short int __elision;
                                                  struct __pthread_internal_list __list;
                                        };
                                        union anonymous$3
                                        {
                                                  struct __pthread_mutex_s __data;
                                                  char __size[40l];
                                                  signed long int __align;
                                        };
                                        struct SF_INFO
                                        {
                                                  signed long int frames;
                                                  signed int samplerate;
                                                  signed int channels;
                                                  signed int format;
                                                  signed int sections;
                                                  signed int seekable;
                                        };
                                        struct _IO_marker
                                        {
                                                  struct _IO_marker *_next;
                                                  struct _IO_FILE *_sbuf;
                                                  signed int _pos;
                                        };
                                        struct _thread_info
                                        {
                                                  unsigned long int thread_id;
                                                  struct SNDFILE_tag *sndfile;
                                                  unsigned int pos;
                                                  struct _jack_client *client;
                                                  unsigned int channels;
                                                  signed int can_process;
                                                  signed int read_done;
                                                  signed int play_done;
                                        };
                                        union pthread_attr_t
                                        {
                                                  char __size[56l];
                                                  signed long int __align;
                                        };
                                        union anonymous$1 data_ready = {.__data = {.__lock = 0, .__futex = (unsigned int) 0, .__total_seq = (unsigned long long int) 0, .__wakeup_seq = (unsigned long long int) 0, .__woken_seq = 
                                        (unsigned long long int) 0, .__mutex = 
                                        0, .__nwaiters = 
                                        (unsigned int) 0, .__broadcast_seq = (unsigned int) 0}};
                                        union anonymous$3 disk_thread_lock = {.__data = {.__lock = 0, .__count = (unsigned int) 0, .__owner = 0, .__nusers = (unsigned int) 0, .__kind = 
                                        0, .__spins = (signed short int) 0, .__elision = 
                                        (signed short int) 0, .__list = {.__prev = (struct __pthread_internal_list *) 0, .__next = (struct __pthread_internal_list *) 0}}};
                                        static struct _jack_port **output_port;
                                        static float **outs;
                                        static struct anonymous$2 *ringbuf;
                                        const unsigned long int sample_size = (sizeof(float));
                                        struct _IO_FILE *stderr;
                                        struct _IO_FILE *stdout;
                                        void *disk_thread_0(void *__cs_param_disk_thread_arg)
                                        {
                                                  static struct _thread_info *__cs_local_disk_thread_info;
IF(1,0,tdisk_thread_0_1)
                                                  __cs_local_disk_thread_info = (struct _thread_info *) __cs_param_disk_thread_arg;
                                                  static signed long int __cs_nondet_disk_thread_buf_avail;
                                                  static signed long int __cs_nondet_disk_thread_read_frames;
                                                  static struct anonymous __cs_nondet_disk_thread_vec[2l];
                                                  static unsigned long int __cs_local_disk_thread_bytes_per_frame;
tdisk_thread_0_1:
IF(1,1,tdisk_thread_0_2)
                                                  if (((1 == __cs_pc[1]) & __cs_dataraceSecondThread) & (__CPROVER_get_field(&sample_size, "dr_write") || __CPROVER_get_field(__cs_local_disk_thread_info, "dr_write")))
                                                            __cs_dataraceNotDetected = 0;
                                                  __cs_local_disk_thread_bytes_per_frame = sample_size * ((unsigned long int) (*__cs_local_disk_thread_info).channels);
                                                  __cs_setcanceltype(1, (signed int *) 0);
tdisk_thread_0_2:
IF(1,2,tdisk_thread_0_3)
                                                  __cs_mutex_lock(&disk_thread_lock, 1);
                                                  if (!((_Bool) 1))
                                                            {
                                                            goto __exit_loop_1;
                                                            ;
                                                  }
                                                  ;
                                                            {
tdisk_thread_0_3:
IF(1,3,tdisk_thread_0_4)
                                                            if (((3 == __cs_pc[1]) & __cs_dataraceSecondThread) & __CPROVER_get_field(&ringbuf, "dr_write"))
                                                                      __cs_dataraceNotDetected = 0;
                                                            jack_ringbuffer_get_write_vector(ringbuf, __cs_nondet_disk_thread_vec);
                                                            __cs_nondet_disk_thread_read_frames = (signed long int) 0;
                                                            ;
                                                            ;
                                                            static _Bool __cs_nondet_disk_thread___cs_tmp_if_cond_0;
                                                            __cs_nondet_disk_thread___cs_tmp_if_cond_0 = !(__cs_nondet_disk_thread_vec[0l].len == 0ul);
                                                            if (__cs_nondet_disk_thread___cs_tmp_if_cond_0)
                                                                                {
                                                                      __cs_nondet_disk_thread_buf_avail = (signed long int) (__cs_nondet_disk_thread_vec[(signed long int) 0].len / __cs_local_disk_thread_bytes_per_frame);
tdisk_thread_0_4:
IF(1,4,tdisk_thread_0_5)
                                                                      if (((4 == __cs_pc[1]) & __cs_dataraceSecondThread) & __CPROVER_get_field(__cs_local_disk_thread_info, "dr_write"))
                                                                                __cs_dataraceNotDetected = 0;
                                                                      __cs_nondet_disk_thread_read_frames = sf_readf_float((*__cs_local_disk_thread_info).sndfile, (float *) __cs_nondet_disk_thread_vec[(signed long int) 0].buf, __cs_nondet_disk_thread_buf_avail);
                                                                      ;
                                                                      ;
                                                                      static _Bool __cs_nondet_disk_thread___cs_tmp_if_cond_1;
                                                                      __cs_nondet_disk_thread___cs_tmp_if_cond_1 = !(__cs_nondet_disk_thread_vec[1l].len == 0ul);
                                                                      if (__cs_nondet_disk_thread___cs_tmp_if_cond_1)
                                                                                                    {
                                                                                __cs_nondet_disk_thread_buf_avail = (signed long int) (__cs_nondet_disk_thread_vec[(signed long int) 1].len / __cs_local_disk_thread_bytes_per_frame);
                                                                                static signed long int __cs_nondet_disk_thread_return_value_sf_readf_float$1;
tdisk_thread_0_5:
IF(1,5,tdisk_thread_0_6)
                                                                                if (((5 == __cs_pc[1]) & __cs_dataraceSecondThread) & __CPROVER_get_field(__cs_local_disk_thread_info, "dr_write"))
                                                                                          __cs_dataraceNotDetected = 0;
                                                                                __cs_nondet_disk_thread_return_value_sf_readf_float$1 = sf_readf_float((*__cs_local_disk_thread_info).sndfile, (float *) __cs_nondet_disk_thread_vec[(signed long int) 1].buf, __cs_nondet_disk_thread_buf_avail);
                                                                                __cs_nondet_disk_thread_read_frames = __cs_nondet_disk_thread_read_frames + __cs_nondet_disk_thread_return_value_sf_readf_float$1;
                                                                      }
                                                                      __CPROVER_assume(__cs_pc_cs[1] >= 6);
                                                                      ;
                                                            }
                                                            __CPROVER_assume(__cs_pc_cs[1] >= 6);
                                                            ;
                                                            ;
                                                            ;
                                                            static _Bool __cs_nondet_disk_thread___cs_tmp_if_cond_2;
                                                            __cs_nondet_disk_thread___cs_tmp_if_cond_2 = __cs_nondet_disk_thread_read_frames == 0l;
                                                            if (__cs_nondet_disk_thread___cs_tmp_if_cond_2)
                                                                                {
                                                                      goto __exit_loop_1;
                                                                      ;
                                                            }
                                                            ;
tdisk_thread_0_6:
IF(1,6,tdisk_thread_0_7)
                                                            if (((6 == __cs_pc[1]) & __cs_dataraceSecondThread) & __CPROVER_get_field(&ringbuf, "dr_write"))
                                                                      __cs_dataraceNotDetected = 0;
                                                            jack_ringbuffer_write_advance(ringbuf, ((unsigned long int) __cs_nondet_disk_thread_read_frames) * __cs_local_disk_thread_bytes_per_frame);
tdisk_thread_0_7:
                                                            if (((7 == __cs_pc_cs[1]) & __cs_dataraceDetectionStarted) & (!__cs_dataraceSecondThread))
                                                            {
                                                                      __CPROVER_set_field(__cs_local_disk_thread_info, "dr_write", 1);
                                                            }
IF(1,7,tdisk_thread_0_8)
                                                            if (((7 == __cs_pc[1]) & __cs_dataraceSecondThread) & __CPROVER_get_field(__cs_local_disk_thread_info, "dr_write"))
                                                                      __cs_dataraceNotDetected = 0;
                                                            (*__cs_local_disk_thread_info).can_process = 1;
tdisk_thread_0_8:
IF(1,8,tdisk_thread_0_9)
                                                            __cs_cond_wait_1(&data_ready, &disk_thread_lock, 1);
tdisk_thread_0_9:
IF(1,9,tdisk_thread_0_10)
                                                            __cs_cond_wait_2(&data_ready, &disk_thread_lock, 1);
                                                            ;
                                                            ;
                                                  }
                                                  ;
tdisk_thread_0_10:
IF(1,10,tdisk_thread_0_11)
                                                  __CPROVER_assume(!((_Bool) 1));
                                                  __exit_loop_1:
                                                  __CPROVER_assume(__cs_pc_cs[1] >= 11);
                                                  ;
                                                  ;
tdisk_thread_0_11:
                                                  if (((11 == __cs_pc_cs[1]) & __cs_dataraceDetectionStarted) & (!__cs_dataraceSecondThread))
                                                  {
                                                            __CPROVER_set_field(__cs_local_disk_thread_info, "dr_write", 1);
                                                  }
IF(1,11,tdisk_thread_0_12)
                                                  if (((11 == __cs_pc[1]) & __cs_dataraceSecondThread) & __CPROVER_get_field(__cs_local_disk_thread_info, "dr_write"))
                                                            __cs_dataraceNotDetected = 0;
                                                  (*__cs_local_disk_thread_info).read_done = 1;
tdisk_thread_0_12:
IF(1,12,tdisk_thread_0_13)
                                                  __cs_mutex_unlock(&disk_thread_lock, 1);
                                                  goto __exit_disk_thread;
                                                  ;
                                                  __exit_disk_thread:
                                                  __CPROVER_assume(__cs_pc_cs[1] >= 13);
                                                  ;
                                                  ;
tdisk_thread_0_13: 
                                                  __cs_exit(0, 1);
                                        }
                                        signed int __cs_main_thread(void)
                                        {
                                                  signed int __cs_param_main_narg;
                                                  char **__cs_param_main_args;
IF(0,0,tmain_1)
                                                  static struct SNDFILE_tag *__cs_nondet_main_sndfile;
                                                  static struct SF_INFO __cs_nondet_main_sndfileinfo;
                                                  static struct _jack_client *__cs_nondet_main_client;
                                                  static struct _thread_info __cs_nondet_main_info;
                                                  static signed int __cs_nondet_main_i;
                                                  static signed int __cs_nondet_main_jack_sr;
                                                  ;
                                                  ;
                                                  static _Bool __cs_nondet_main___cs_tmp_if_cond_3;
                                                  __cs_nondet_main___cs_tmp_if_cond_3 = !(__cs_param_main_narg >= 2);
                                                  if (__cs_nondet_main___cs_tmp_if_cond_3)
                                                            {
                                                            fprintf(stderr, "no soundfile given\n");
                                                            goto __exit_main;
                                                            ;
                                                  }
                                                  else
                                                            {
                                                            __cs_nondet_main_client = jack_client_new("jackplay");
                                                            ;
                                                            ;
                                                            static _Bool __cs_nondet_main___cs_tmp_if_cond_4;
                                                            __cs_nondet_main___cs_tmp_if_cond_4 = __cs_nondet_main_client == ((struct _jack_client *) 0);
                                                            if (__cs_nondet_main___cs_tmp_if_cond_4)
                                                                                {
                                                                      fprintf(stderr, "Jack server not running?\n");
                                                                      goto __exit_main;
                                                                      ;
                                                            }
                                                            else
                                                                                {
                                                                      static unsigned int __cs_nondet_main_return_value_jack_get_sample_rate$1;
                                                                      __cs_nondet_main_return_value_jack_get_sample_rate$1 = jack_get_sample_rate(__cs_nondet_main_client);
                                                                      __cs_nondet_main_jack_sr = (signed int) __cs_nondet_main_return_value_jack_get_sample_rate$1;
                                                                      __cs_nondet_main_sndfileinfo.format = 0;
                                                                      __cs_nondet_main_sndfile = sf_open(__cs_param_main_args[(signed long int) 1], 16, &__cs_nondet_main_sndfileinfo);
                                                                      ;
                                                                      ;
                                                                      static _Bool __cs_nondet_main___cs_tmp_if_cond_5;
                                                                      __cs_nondet_main___cs_tmp_if_cond_5 = __cs_nondet_main_sndfile == ((struct SNDFILE_tag *) 0);
                                                                      if (__cs_nondet_main___cs_tmp_if_cond_5)
                                                                                                    {
                                                                                fprintf(stderr, "Could not open soundfile '%s'\n", __cs_param_main_args[(signed long int) 1]);
                                                                                goto __exit_main;
                                                                                ;
                                                                      }
                                                                      else
                                                                                                    {
                                                                                fprintf(stderr, "Channels    : %d\nSample rate : %d Hz\nDuration    : ", __cs_nondet_main_sndfileinfo.channels, __cs_nondet_main_sndfileinfo.samplerate);
                                                                                                                        {
                                                                                          static unsigned int __cs_param_print_time_1_pos;
                                                                                          __cs_param_print_time_1_pos = (unsigned int) __cs_nondet_main_sndfileinfo.frames;
                                                                                          static signed int __cs_param_print_time_1_jack_sr;
                                                                                          __cs_param_print_time_1_jack_sr = __cs_nondet_main_sndfileinfo.samplerate;
                                                                                          static float __cs_local_print_time_1_sec;
                                                                                          __cs_local_print_time_1_sec = (float) (((double) __cs_param_print_time_1_pos) / (1.0 * ((double) __cs_param_print_time_1_jack_sr)));
                                                                                          static signed int __cs_local_print_time_1_min;
                                                                                          __cs_local_print_time_1_min = (signed int) (((double) __cs_local_print_time_1_sec) / 60.0);
                                                                                          static double __cs_nondet_print_time_1_return_value_fmod$1;
                                                                                          __cs_nondet_print_time_1_return_value_fmod$1 = fmod((double) __cs_local_print_time_1_sec, 60.0);
                                                                                          fprintf(stderr, "%02d:%05.2f", __cs_local_print_time_1_min, __cs_nondet_print_time_1_return_value_fmod$1);
                                                                                          __exit_print_time_1:
                                                                                          __CPROVER_assume(__cs_pc_cs[0] >= 1);
                                                                                          ;
                                                                                          ;
                                                                                }
                                                                                ;
                                                                                fprintf(stderr, "\n");
                                                                                ;
                                                                                ;
                                                                                static _Bool __cs_nondet_main___cs_tmp_if_cond_6;
                                                                                __cs_nondet_main___cs_tmp_if_cond_6 = !(__cs_nondet_main_sndfileinfo.samplerate == __cs_nondet_main_jack_sr);
                                                                                if (__cs_nondet_main___cs_tmp_if_cond_6)
                                                                                                                        {
                                                                                          fprintf(stderr, "Warning: samplerate of soundfile (%d Hz) does not match jack server (%d Hz).\n", __cs_nondet_main_sndfileinfo.samplerate, __cs_nondet_main_jack_sr);
                                                                                }
                                                                                ;
                                                                                memset((void *) (&__cs_nondet_main_info), 0, 20);
                                                                                __cs_nondet_main_info.can_process = 0;
                                                                                __cs_nondet_main_info.read_done = 0;
                                                                                __cs_nondet_main_info.play_done = 0;
                                                                                __cs_nondet_main_info.sndfile = __cs_nondet_main_sndfile;
                                                                                __cs_nondet_main_info.channels = (unsigned int) __cs_nondet_main_sndfileinfo.channels;
                                                                                __cs_nondet_main_info.client = __cs_nondet_main_client;
                                                                                __cs_nondet_main_info.pos = (unsigned int) 0;
                                                                                jack_set_process_callback(__cs_nondet_main_client, process, (void *) (&__cs_nondet_main_info));
                                                                                jack_on_shutdown(__cs_nondet_main_client, jack_shutdown, 0);
                                                                                static void *__cs_nondet_main_return_value_calloc$2;
                                                                                __cs_nondet_main_return_value_calloc$2 = calloc((unsigned long int) __cs_nondet_main_sndfileinfo.channels, 20 * (sizeof(char)));
                                                                                output_port = (struct _jack_port **) __cs_nondet_main_return_value_calloc$2;
                                                                                static void *__cs_nondet_main_return_value_calloc$3;
                                                                                __cs_nondet_main_return_value_calloc$3 = calloc((unsigned long int) __cs_nondet_main_sndfileinfo.channels, sizeof(float *));
                                                                                outs = (float **) __cs_nondet_main_return_value_calloc$3;
                                                                                __cs_nondet_main_i = 0;
                                                                                if (!(!(__cs_nondet_main_i >= __cs_nondet_main_sndfileinfo.channels)))
                                                                                                                        {
                                                                                          goto __exit_loop_2;
                                                                                          ;
                                                                                }
                                                                                ;
                                                                                                                        {
                                                                                          static char *__cs_nondet_main_name;
                                                                                          ;
                                                                                          ;
                                                                                          snprintf(__cs_nondet_main_name, sizeof(char [16l]), "out_%d", __cs_nondet_main_i + 1);
                                                                                          output_port[(signed long int) __cs_nondet_main_i] = jack_port_register(__cs_nondet_main_client, __cs_nondet_main_name, "32 bit float mono audio", (unsigned long int) 2, (unsigned long int) 0);
                                                                                          ;
                                                                                          ;
                                                                                          __cs_nondet_main_i = __cs_nondet_main_i + 1;
                                                                                }
                                                                                ;
                                                                                __CPROVER_assume(!(!(__cs_nondet_main_i >= __cs_nondet_main_sndfileinfo.channels)));
                                                                                __exit_loop_2:
                                                                                __CPROVER_assume(__cs_pc_cs[0] >= 1);
                                                                                ;
                                                                                ;
                                                                                ringbuf = jack_ringbuffer_create((sizeof(float)) * ((unsigned long int) (1 << 16)));
                                                                                memset((void *) (*ringbuf).buf, 0, 128);
                                                                                static signed int __cs_nondet_main_return_value_jack_activate$4;
                                                                                __cs_nondet_main_return_value_jack_activate$4 = jack_activate(__cs_nondet_main_client);
                                                                                ;
                                                                                ;
                                                                                static _Bool __cs_nondet_main___cs_tmp_if_cond_7;
                                                                                __cs_nondet_main___cs_tmp_if_cond_7 = !(__cs_nondet_main_return_value_jack_activate$4 == 0);
                                                                                if (__cs_nondet_main___cs_tmp_if_cond_7)
                                                                                                                        {
                                                                                          fprintf(stderr, "Cannot activate client.\n");
                                                                                          goto __exit_main;
                                                                                          ;
                                                                                }
                                                                                else
                                                                                                                        {
                                                                                          __cs_nondet_main_i = 0;
                                                                                          if (!(!(__cs_nondet_main_i >= __cs_nondet_main_sndfileinfo.channels)))
                                                                                                                                            {
                                                                                                    goto __exit_loop_3;
                                                                                                    ;
                                                                                          }
                                                                                          ;
                                                                                                                                            {
                                                                                                    static char *__cs_nondet_main_main$$1$$6$$1$$name;
                                                                                                    ;
                                                                                                    ;
                                                                                                    snprintf(__cs_nondet_main_main$$1$$6$$1$$name, sizeof(char [64l]), "alsa_pcm:playback_%d", __cs_nondet_main_i + 1);
                                                                                                    const char *__cs_nondet_main_return_value_jack_port_name$5;
                                                                                                    __cs_nondet_main_return_value_jack_port_name$5 = jack_port_name(output_port[(signed long int) __cs_nondet_main_i]);
                                                                                                    static signed int __cs_nondet_main_return_value_jack_connect$6;
                                                                                                    __cs_nondet_main_return_value_jack_connect$6 = jack_connect(__cs_nondet_main_client, __cs_nondet_main_return_value_jack_port_name$5, __cs_nondet_main_main$$1$$6$$1$$name);
                                                                                                    ;
                                                                                                    ;
                                                                                                    static _Bool __cs_nondet_main___cs_tmp_if_cond_8;
                                                                                                    __cs_nondet_main___cs_tmp_if_cond_8 = !(__cs_nondet_main_return_value_jack_connect$6 == 0);
                                                                                                    if (__cs_nondet_main___cs_tmp_if_cond_8)
                                                                                                                                                                {
                                                                                                              fprintf(stderr, "Cannot connect output port %d (%s).\n", __cs_nondet_main_i, (const void *) __cs_nondet_main_main$$1$$6$$1$$name);
                                                                                                    }
                                                                                                    ;
                                                                                                    ;
                                                                                                    ;
                                                                                                    __cs_nondet_main_i = __cs_nondet_main_i + 1;
                                                                                          }
                                                                                          ;
                                                                                          __CPROVER_assume(!(!(__cs_nondet_main_i >= __cs_nondet_main_sndfileinfo.channels)));
                                                                                          __exit_loop_3:
                                                                                          __CPROVER_assume(__cs_pc_cs[0] >= 1);
                                                                                          ;
                                                                                          ;
                                                                                          __cs_create(&__cs_nondet_main_info.thread_id, (const union pthread_attr_t *) 0, disk_thread_0, (void *) (&__cs_nondet_main_info), 1);
                                                                                          if (!(__cs_nondet_main_info.play_done == 0))
                                                                                                                                            {
                                                                                                    goto __exit_loop_4;
                                                                                                    ;
                                                                                          }
                                                                                          ;
                                                                                                                                            {
tmain_1:
IF(0,1,tmain_2)
                                                                                                    if (((1 == __cs_pc[0]) & __cs_dataraceSecondThread) & __CPROVER_get_field(&stderr, "dr_write"))
                                                                                                              __cs_dataraceNotDetected = 0;
                                                                                                    fprintf(stderr, "\r-> ");
                                                                                                                                                                {
                                                                                                              static unsigned int __cs_param_print_time_2_pos;
                                                                                                              __cs_param_print_time_2_pos = __cs_nondet_main_info.pos;
                                                                                                              static signed int __cs_param_print_time_2_jack_sr;
                                                                                                              __cs_param_print_time_2_jack_sr = __cs_nondet_main_jack_sr;
                                                                                                              static float __cs_local_print_time_2_sec;
                                                                                                              __cs_local_print_time_2_sec = (float) (((double) __cs_param_print_time_2_pos) / (1.0 * ((double) __cs_param_print_time_2_jack_sr)));
                                                                                                              static signed int __cs_local_print_time_2_min;
                                                                                                              __cs_local_print_time_2_min = (signed int) (((double) __cs_local_print_time_2_sec) / 60.0);
                                                                                                              static double __cs_nondet_print_time_2_return_value_fmod$1;
                                                                                                              __cs_nondet_print_time_2_return_value_fmod$1 = fmod((double) __cs_local_print_time_2_sec, 60.0);
tmain_2:
IF(0,2,tmain_3)
                                                                                                              if (((2 == __cs_pc[0]) & __cs_dataraceSecondThread) & __CPROVER_get_field(&stderr, "dr_write"))
                                                                                                                        __cs_dataraceNotDetected = 0;
                                                                                                              fprintf(stderr, "%02d:%05.2f", __cs_local_print_time_2_min, __cs_nondet_print_time_2_return_value_fmod$1);
                                                                                                              __exit_print_time_2:
                                                                                                              __CPROVER_assume(__cs_pc_cs[0] >= 3);
                                                                                                              ;
                                                                                                              ;
                                                                                                    }
                                                                                                    ;
tmain_3:
IF(0,3,tmain_4)
                                                                                                    if (((3 == __cs_pc[0]) & __cs_dataraceSecondThread) & __CPROVER_get_field(&stdout, "dr_write"))
                                                                                                              __cs_dataraceNotDetected = 0;
                                                                                                    fflush(stdout);
                                                                                                    usleep((unsigned int) 50000);
                                                                                          }
                                                                                          ;
tmain_4:
IF(0,4,tmain_5)
                                                                                          __CPROVER_assume(!(__cs_nondet_main_info.play_done == 0));
                                                                                          __exit_loop_4:
                                                                                          __CPROVER_assume(__cs_pc_cs[0] >= 5);
                                                                                          ;
                                                                                          ;
tmain_5:
IF(0,5,tmain_6)
                                                                                          jack_client_close(__cs_nondet_main_client);
tmain_6:
IF(0,6,tmain_7)
                                                                                          if (((6 == __cs_pc[0]) & __cs_dataraceSecondThread) & __CPROVER_get_field(&ringbuf, "dr_write"))
                                                                                                    __cs_dataraceNotDetected = 0;
                                                                                          jack_ringbuffer_free(ringbuf);
tmain_7:
IF(0,7,tmain_8)
                                                                                          sf_close(__cs_nondet_main_sndfile);
tmain_8:
IF(0,8,tmain_9)
                                                                                          if (((8 == __cs_pc[0]) & __cs_dataraceSecondThread) & __CPROVER_get_field(&outs, "dr_write"))
                                                                                                    __cs_dataraceNotDetected = 0;
                                                                                          free((void *) outs);
tmain_9:
IF(0,9,tmain_10)
                                                                                          if (((9 == __cs_pc[0]) & __cs_dataraceSecondThread) & __CPROVER_get_field(&output_port, "dr_write"))
                                                                                                    __cs_dataraceNotDetected = 0;
                                                                                          free((void *) output_port);
                                                                                          puts("");
                                                                                          goto __exit_main;
                                                                                          ;
                                                                                }
                                                                                __CPROVER_assume(__cs_pc_cs[0] >= 10);
                                                                                ;
                                                                      }
                                                                      __CPROVER_assume(__cs_pc_cs[0] >= 10);
                                                                      ;
                                                            }
                                                            __CPROVER_assume(__cs_pc_cs[0] >= 10);
                                                            ;
                                                  }
                                                  __CPROVER_assume(__cs_pc_cs[0] >= 10);
                                                  ;
                                                  __exit_main:
                                                  __CPROVER_assume(__cs_pc_cs[0] >= 10);
                                                  ;
                                                  ;
tmain_10: 
                                                  __cs_exit(0, 0);
                                        }
                                        int main(void)
                                        {
                                                  __CPROVER_field_decl_global("dr_write", (_Bool) 0);
                                                  unsigned __CPROVER_bitvector[1] __cs_dr_ts;
                                                  __CPROVER_assume(__cs_dr_ts <= 1);
/* round  0 */
/* main */
                                                  unsigned __CPROVER_bitvector[4] __cs_tmp_t0_r0;
                                                  __cs_pc_cs[0] = __cs_tmp_t0_r0;
                                                  __CPROVER_assume(__cs_pc_cs[0] > 0);
                                                  __CPROVER_assume(__cs_pc_cs[0] <= 10);
                                                  if (__cs_dr_ts == 0)
                                                            __cs_dataraceDetectionStarted = 1;
                                                  __cs_main_thread();
                                                  if (__cs_dataraceDetectionStarted)
                                                            __cs_dataraceSecondThread = 1;
                                                  __cs_pc[0] = __cs_pc_cs[0];
/* disk_thread_0 */
                                                  unsigned __CPROVER_bitvector[4] __cs_tmp_t1_r0;
                                                  if (__cs_dataraceContinue & __cs_active_thread[1])
                                                  {
                                                            __cs_pc_cs[1] = __cs_tmp_t1_r0;
                                                            __CPROVER_assume(__cs_pc_cs[1] <= 13);
                                                            if (__cs_dr_ts == 1)
                                                                      __cs_dataraceDetectionStarted = 1;
                                                            disk_thread_0(__cs_threadargs[1]);
                                                            if (__cs_dataraceSecondThread & (__cs_tmp_t1_r0 > __cs_pc[1]))
                                                                      __cs_dataraceContinue = 0;
                                                            if (__cs_dataraceDetectionStarted)
                                                                      __cs_dataraceSecondThread = 1;
                                                            __cs_pc[1] = __cs_pc_cs[1];
                                                  }
                                                  unsigned __CPROVER_bitvector[4] __cs_tmp_t0_r1;
                                                  if (((__cs_dr_ts > (-2)) & __cs_dataraceContinue) & __cs_active_thread[0])
                                                  {
                                                            __cs_pc_cs[0] = __cs_pc[0] + __cs_tmp_t0_r1;
                                                            __CPROVER_assume(__cs_pc_cs[0] >= __cs_pc[0]);
                                                            __CPROVER_assume(__cs_pc_cs[0] <= 10);
                                                            __cs_main_thread();
                                                  }
                                                  __CPROVER_assert(__cs_dataraceNotDetected, "Data race failure");
                                                  return 0;
                                        }
                                        
